print("welcome to the Interactive Personal Data Collector!")
print()
Name=input("please ernter your name: ")
Age=int(input("please enter your age: "))
Height=float(input("please enter your height in meters: "))
Favourite_Number=int(input("please enter your favourite number: "))
print()
print("Thank you! Here is the information we collected:")
print("Name:",Name,"(",type(Name), "Memory Address:",id(Name), Name,")")
print("Age:",Age,"(",type(Age), "Memory Address:",id(Age), Age,")")
print("Height:",Height,"(",type(Height), "Memory Address:",id(Age), Age,")")
print("Favourite Number:",Favourite_Number,"(",type(Favourite_Number), "Memory Address:",id(Favourite_Number), Favourite_Number,")")
print()
print("Thank you for using the Personal Data Collector. Goodbye!")

